<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb62fa27c47e313b4b070603c716db8e9
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'Rede\\' => 5,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Rede\\' => 
        array (
            0 => __DIR__ . '/..' . '/developersrede/erede-php/src/Rede',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb62fa27c47e313b4b070603c716db8e9::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb62fa27c47e313b4b070603c716db8e9::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb62fa27c47e313b4b070603c716db8e9::$classMap;

        }, null, ClassLoader::class);
    }
}
